cmake-fail: updated libsdk cmake to utilise CSDK_DIR
edgexfoundry-holding/device-bluetooth-c pull request #24
Opened 2020-04-08 10:25 UTC by FraserG01

Based on issue raised by @tonyespy in https://github.com/edgexfoundry-holding/device-bluetooth-c/pull/22

@tonyespy could you check this change allows you to build the device service now?

2020-04-08 16:18 UTC, iain-anderson requested changes
Doesn't work for me, you need to add LIBCSDK_INCLUDE_DIR to include_directories

2020-04-09 07:40 UTC, FraserG01 commented
> Doesn't work for me, you need to add LIBCSDK_INCLUDE_DIR to include_directories

change made

2020-04-09 11:30 UTC, iain-anderson approved these changes
LGTM

2020-04-09 12:04 UTC, merged

2020-04-11 19:52 UTC, tonyespy commented
@FraserG01 It works for me now too, thanks!